#!/usr/bin/env bash
set -euo pipefail
trap 'echo "$0: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[@]}")" && pwd)"
WORKSPACE="$(realpath "$SCRIPT_DIR/..")"

fd -t f . "$WORKSPACE/scripts" "$WORKSPACE/guest" | xargs shellcheck
